import { Prisma } from '@prisma/client';

export const mangaList = [
  {
    name: 'Berserk Vol. 41',
    author: 'Kentarou Miura',
    genreCodes: [0, 1, 2, 3, 4, 5, 6].map((e) => ({ genreId: e })),
    description: `Apesar de Caska ter recuperado a consciência, ela não pode se livrar dos traumas do passado. E nada pode engatilhar essas memórias mais do que o espadachim negro, que enfrentou os mesmos horrores em sua aventura de trazer Caska a um lugar onde ela pudesse ser curada. Porém a reaparição de um garoto mudo e estranho pode ser a chave para trazer paz à alma sofrida de Caska.`,
    image: 'https://m.media-amazon.com/images/I/81+xh1mRSTL.jpg',
    inStock: 8,
    price: new Prisma.Decimal(83.76),
    rating: 1,
  },
  {
    name: 'Vagabond Vol. 37',
    author: 'Takehiko Inoue',
    genreCodes: [0, 1, 2].map((e) => ({ genreId: e })),
    description: `Viver pela espada e se transformar no demônio... Viver pela terra e na morte voltar a ela... Musashi, em sua luta árdua e solitária persegue o ápice da força que durará enquanto durar sua vida. Enquanto que Shusaku, trabalha a terra para preservar a força vital para o mundo futuro. Dois modos de viver, impossíveis de se entenderem de tão antagônicos que são, se cruzam e frutificam uma ligação inesperada através dos cuidados necessários no cultivo das frágeis mudas de arroz.`,
    image: 'https://m.media-amazon.com/images/I/91EghdEQD3L.jpg',
    inStock: 5,
    price: new Prisma.Decimal(26.76),
    rating: 1,
  },
  {
    name: 'One Piece Vol. 102',
    author: 'Eiichiro Oda',
    genreCodes: [0, 1, 7, 3, 8].map((e) => ({ genreId: e })),
    description: `Luffy está de volta e desafia Kaido mais uma vez! A batalha entre esses dois piratas colossais começa a caminhar para a sua conclusão!! Enquanto isso, chegou a hora dos companheiros de Luffy decidirem seus confrontos contra os poderosos oficiais do bando inimigo!!`,
    image: 'https://m.media-amazon.com/images/I/71uoUEo8D1L.jpg',
    inStock: 20,
    price: new Prisma.Decimal(32.9),
    rating: 1,
  },
  {
    name: 'Slam Dunk Vol. 24',
    author: 'Takehiko Inoue',
    genreCodes: [7, 2, 9].map((e) => ({ genreId: e })),
    description: `Restando dois minutos para o final da partida, o Shohoku está a cinco pontos atrás do Sanno. Arriscando o orgulho como time colegial número um do Japão, o Sanno parte em um ataque desesperado para ganhar vantagem no placar. Finalmente, o embate entre Sanno e Shohoku chega a uma emocionante conclusão!`,
    image: 'https://m.media-amazon.com/images/I/6181PZ7ma1L.jpg',
    inStock: 8,
    price: new Prisma.Decimal(44.9),
    rating: 1,
  },
  {
    name: 'Fullmetal Alchemist Vol. 27',
    author: 'Hiromu Arakawa',
    genreCodes: [0, 1, 7, 2, 3, 8].map((e) => ({ genreId: e })),
    description: `Ed está encurralado frente ao inimigo mais forte da humanidade. A chance de vitória é quase nula, mas o alquimista não vai desistir! Diante da Verdade, o que Ed e Al obtiveram foi…! Eis o fim da jornada dos irmãos Elric.`,
    image: 'https://m.media-amazon.com/images/I/61FjXfDGAxL.jpg',
    inStock: 14,
    price: new Prisma.Decimal(22.42),
    rating: 1,
  },
  {
    name: 'Haikyu!! Vol. 5',
    author: 'Haruichi Furudate',
    genreCodes: [7, 2, 9].map((e) => ({ genreId: e })),
    description: `Durante o amistoso de treino com o colégio Nekoma, antigo e fatídico rival do Karasuno, a dupla busca novas possibilidades de ataque. Após perder o jogo, e jurando uma revanche contra o Nekoma no Torneio Nacional, o Karasuno se prepara para o desafio do Intercolegial!`,
    image: 'https://m.media-amazon.com/images/I/81WW4EVhrrL.jpg',
    inStock: 10,
    price: new Prisma.Decimal(34.99),
    rating: 1,
  },
  {
    name: 'Boa Noite Punpun Vol. 7',
    author: 'Inio Asano',
    genreCodes: [2, 5, 10].map((e) => ({ genreId: e })),
    description: `Punpun e Aiko abandonam tudo e fogem para outra cidade. Qual o destino reservado para o casal que apenas quer ser feliz? Eis o volume final de Boa Noite Punpun.`,
    image: 'https://m.media-amazon.com/images/I/41+Oop2uRTL.jpg',
    inStock: 13,
    price: new Prisma.Decimal(37.42),
    rating: 1,
  },
  {
    name: 'Chainsaw Man Vol. 10',
    author: 'Tatsuki Fujimoto',
    genreCodes: [0, 7, 2, 4, 11].map((e) => ({ genreId: e })),
    description: `“Eu matei o Aki...”Denji está desesperado e com a cabeça nos ares, então, resolve pedir ajuda à Makima.  Entretanto, o consolo temporário fornecido por ela não passou do prelúdio de um pesadelo ainda pior... Quando a porta proibida na mente de Denji se abre, as verdadeiras intenções de Makima e o segredo do Demônio da Motosserra se cruzam transformando tudo em um inferno sangrento!!`,
    image: 'https://m.media-amazon.com/images/I/61pElhi5lsL.jpg',
    inStock: 24,
    price: new Prisma.Decimal(28.8),
    rating: 1,
  },
  {
    name: 'One-Punch Man Vol. 25',
    author: 'Yusuke Murata',
    genreCodes: [0, 7, 12, 11, 8].map((e) => ({ genreId: e })),
    description: `No labirinto subterrâneo, Puripuri-prisoner se depara inesperadamente com Garou, o caçador de heróis, que está cada vez mais forte. Enquanto isso, Saitama passa a acompanhar Senkou no Flash. Na superfície, os heróis de classe “A” estão prestes a serem derrotados pela criatura Nyan, mas eis que surge Kudo Kishi!`,
    image: 'https://m.media-amazon.com/images/I/615tN9zKPML.jpg',
    inStock: 13,
    price: new Prisma.Decimal(28.8),
    rating: 1,
  },
  {
    name: 'Spy X Family Vol. 2',
    author: 'Tatsuya Endo',
    genreCodes: [0, 7, 10, 11].map((e) => ({ genreId: e })),
    description: `Com a missão de proteger a paz entre Ostania e Westalis, a família Forger encara o desafio do Exame de Admissão de um renomado colégio. Porém, para se aproximar de Desmond, o alvo, Anya precisa se tornar uma Aluna Excelente!! Twilight então põe em prática o "Plano da Amizade"...?!`,
    image: 'https://m.media-amazon.com/images/I/81HyHBcpKhL.jpg',
    inStock: 21,
    price: new Prisma.Decimal(34.9),
    rating: 1,
  },
  {
    name: 'Shingeki no kyojin Vol. 14',
    author: 'Hajime Isayama',
    genreCodes: [0, 2, 3, 13, 6].map((e) => ({ genreId: e })),
    description: `O comandante da Divisão de Reconhecimento, Erwin, levanta uma teoria em relação à condição especial de Eren e à humanidade cercada pelas muralhas, e coloca em prática um plano extremamente ambicioso, que pode gerar uma reviravolta política!`,
    image: 'https://m.media-amazon.com/images/I/513L0p8ayFL.jpg',
    inStock: 23,
    price: new Prisma.Decimal(20.3),
    rating: 1,
  },
  {
    name: 'As Egocêntricas Maldições de Souichi (volume único)',
    author: 'Junji Ito',
    genreCodes: [4, 13, 11].map((e) => ({ genreId: e })),
    description: `Souichi Tsujii, um garoto antissocial, é apaixonado por tudo que há de perverso e oculto e se diverte com o seu suposto poder de lançar perigosas maldições em qualquer oportunidade, principalmente ao ser contrariado! E quando seus primos Michina e Yusuke começam a frequentar sua casa nas férias, ele ganha novos alvos para atormentar.`,
    image: 'https://m.media-amazon.com/images/I/81gK4PgrZzL.jpg',
    inStock: 22,
    price: new Prisma.Decimal(58.0),
    rating: 1,
  },
  {
    name: 'CALAFRIOS: Seleção de contos favoritos de Junji Ito',
    author: 'Junji Ito',
    genreCodes: [4, 13, 11].map((e) => ({ genreId: e })),
    description: `Um disco misterioso que fascina de maneira sinistra todos que o ouvem; balões assassinos que têm o formato da cabeça de suas vítimas; uma modelo fotográfica que perturba a mente daqueles que a veem; uma casa tomada por gordura com dois moradores nojentos; um homem atormentado por sonhos que duram séculos... Essas são apenas algumas das tramas grotescamente inventivas reunidas nesta edição.`,
    image: 'https://m.media-amazon.com/images/I/91jjaU0HYbL.jpg',
    inStock: 38,
    price: new Prisma.Decimal(56.9),
    rating: 1,
  },
  {
    name: 'Demon Slayer - Kimetsu No Yaiba Vol. 1',
    author: 'Koyoharu Gotouge',
    genreCodes: [0, 1, 2, 11, 8].map((e) => ({ genreId: e })),
    description: `O dia-a-dia pacato de Tanjiro, um gentil garoto que vende carvão, se transforma radicalmente quando sua família é assassinada por um demônio. A única sobrevivente é Nezuko, sua irmã mais nova. Porém, agora, ela se transformou em um Oni. Diante dessa tragédia, os dois irmãos partem em uma jornada para derrotar o Oni que matou sua mãe e irmãozinhos. E assim tem início uma aventura sanguinolenta de espadachins!`,
    image: 'https://m.media-amazon.com/images/I/51W6wPKu6JL.jpg',
    inStock: 14,
    price: new Prisma.Decimal(25.99),
    rating: 1,
  },
  {
    name: 'Naruto Vol. 64',
    author: 'Masashi Kishimoto',
    genreCodes: [0, 1, 11, 8].map((e) => ({ genreId: e })),
    description: `Kakashi fica abalado ao descobrir que o homem da máscara é seu antigo companheiro, Obito. Porém, as palavras de Naruto fazem com que ele se levante novamente! "Não vou deixar que os meus amigos sejam mortos!!!", ele exclama e parte para o ataque! Mas eis que a Jyuubi ressurge...?!`,
    image: 'https://m.media-amazon.com/images/I/91XAvupIyzL.jpg',
    inStock: 25,
    price: new Prisma.Decimal(18.9),
    rating: 1,
  },
  {
    name: 'Dragon Ball Vol. 23',
    author: 'Akira Toriyama',
    genreCodes: [0, 1, 7, 12, 8].map((e) => ({ genreId: e })),
    description: `Enquanto esperam Goku chegar, Kulilin e Gohan se veem obrigados a se unir com Vegeta para combater as Forças Especiais Ginyu, a tropa de elite do Freeza.`,
    image: 'https://m.media-amazon.com/images/I/81pT4Sc-ukL.jpg',
    inStock: 18,
    price: new Prisma.Decimal(21.2),
    rating: 1,
  },
  {
    name: 'Jujutsu Kaisen Vol. 1',
    author: 'Gege Akutami',
    genreCodes: [0, 2, 11, 8].map((e) => ({ genreId: e })),
    description: `Apesar do estudante colegial Yuuji Itadori ter grande força física, ele se inscreve no Clube de Ocultismo. Certo dia, eles encontram um "objeto amaldiçoado" e retiram o selo, atraindo criaturas chamadas de "maldições". Itadori corre em socorro de seus colegas, mas será que ele será capaz de abater essas criaturas usando apenas a força física?!`,
    image: 'https://m.media-amazon.com/images/I/51ozeKHyYZS.jpg',
    inStock: 15,
    price: new Prisma.Decimal(25.99),
    rating: 1,
  },
  {
    name: 'Berserk Vol. 40',
    author: 'Kentarou Miura',
    genreCodes: [0, 1, 2, 3, 4, 5, 6].map((e) => ({ genreId: e })),
    description: `Gatts e seus companheiros conseguiram chegar ao seu destino, a Ilha dos Elfos, e encontram a Rainha dos Elfos! Shierke e Farnese adentram os corredores dos sonhos de Caska e coletam fragmentos de memória para recuperar sua razão. Griffith e seu exército enfrentam os monstros gigantes e, para retornarem ao lar, devem passar pela Árvore do Mundo.`,
    image:
      'https://m.media-amazon.com/images/I/51Eh4XRiL0L._SX614_BO1,204,203,200_.jpg',
    inStock: 12,
    price: new Prisma.Decimal(22.3),
    rating: 1,
  },
  {
    name: 'Vagabond Vol. 36',
    author: 'Takehiko Inoue',
    genreCodes: [0, 1, 2].map((e) => ({ genreId: e })),
    description: `Não carregar nada... Ser como a água e a terra. Ser a parte e o todo. Por outro lado, Musashi contraria os a natureza, construindo canais e preparando a terra para o plantio, enquanto convive com Iori, a “criança da terra”, que acabou de perder o pai.`,
    image: 'https://m.media-amazon.com/images/I/815zo0-u3fL.jpg',
    inStock: 6,
    price: new Prisma.Decimal(23.54),
    rating: 1,
  },
  {
    name: 'One Piece Vol. 101',
    author: 'Eiichiro Oda',
    genreCodes: [0, 1, 7, 3, 8].map((e) => ({ genreId: e })),
    description: `Acreditando que Luffy voltará e não desistirá de derrubar Kaido, seus companheiros travam batalhas mortais e intensas contra os Oficiais do bando inimigo!! Enquanto isso, é no topo de Onigashima que Kaido e Yamato estão frente a frente dando início a um confronto fatídico entre pai e filha!!`,
    image: 'https://m.media-amazon.com/images/I/71RLbSEF85L.jpg',
    inStock: 18,
    price: new Prisma.Decimal(32.9),
    rating: 1,
  },
  {
    name: 'Fullmetal Alchemist Vol. 26',
    author: 'Hiromu Arakawa',
    genreCodes: [0, 1, 7, 2, 3, 8].map((e) => ({ genreId: e })),
    description: `Os cinco sacrifícios foram reunidos diante do Homúnculo original. A hora do círculo de transmutação em escala nacional ser ativada se aproxima, e a escuridão começa a cobrir o mundo! O inimigo é um, mas com um poder imenso! A jornada dos jovens alquimistas Ed e Al se aproxima do fim…`,
    image: 'https://m.media-amazon.com/images/I/61WQwCQtD-L.jpg',
    inStock: 13,
    price: new Prisma.Decimal(23.9),
    rating: 1,
  },
  {
    name: 'Boa Noite Punpun Vol. 6',
    author: 'Inio Asano',
    genreCodes: [2, 5, 10].map((e) => ({ genreId: e })),
    description: `Depois de finalmente se encontrar com a garota por quem era apaixonado desde pequeno, Punpun se sente realizado. Porém, esse encontro abriu as portas para um futuro de desespero, do qual eles não podem escapar.`,
    image: 'https://m.media-amazon.com/images/I/518Kun7r0EL.jpg',
    inStock: 11,
    price: new Prisma.Decimal(43.64),
    rating: 1,
  },
  {
    name: 'Naruto Vol. 61',
    author: 'Masashi Kishimoto',
    genreCodes: [0, 1, 11, 8].map((e) => ({ genreId: e })),
    description: `O poder absurdo de Madara Uchiha não permite que nem os cinco Kages se aproximem. Tsunade toma uma atitude que vai contra as regras dos ninjas médicos?! E Itachi e Sasuke encaram Kabuto, a fim de parar o Edotensei. A fatídica batalha que pode decidir a guerra começa agora...!!`,
    image: 'https://m.media-amazon.com/images/I/91mKHq6OB8L.jpg',
    inStock: 25,
    price: new Prisma.Decimal(18.9),
    rating: 1,
  },
  {
    name: 'Dragon Ball Vol. 24',
    author: 'Akira Toriyama',
    genreCodes: [0, 1, 7, 12, 8].map((e) => ({ genreId: e })),
    description: `Quando as setes esferas, enfim, estavam reunidas, eis que surgem as Forças Especiais Ginyu para ajudar Freeza. Durante a batalha, o comandante Ginyu trocou de corpo com Goku e...!`,
    image: 'https://m.media-amazon.com/images/I/81OKQnDWVrL.jpg',
    inStock: 19,
    price: new Prisma.Decimal(21.2),
    rating: 1,
  },
  {
    name: 'Berserk Vol. 39',
    author: 'Kentarou Miura',
    genreCodes: [0, 1, 2, 3, 4, 5, 6].map((e) => ({ genreId: e })),
    description: `Depois de destruir o Deus do Mar, que estava alojado em uma ilha solitária, o grupo de Guts finalmente chega a Elfhelm, a terra natal de Puck. De imediato, eles vão ao encontro da Rainha dos Elfos, aquela que dizem ser capaz de restaurar a sanidade de Caska. Porém...`,
    image: 'https://m.media-amazon.com/images/I/81-1XTOfWQL.jpg',
    inStock: 15,
    price: new Prisma.Decimal(22.3),
    rating: 1,
  },
  {
    name: 'Vagabond Vol. 35',
    author: 'Takehiko Inoue',
    genreCodes: [0, 1, 2].map((e) => ({ genreId: e })),
    description: `Nada carregar... Ser como a água e ser como a terra. Ser o “elemento” e ser o “todo”. Por outro lado, Musashi resiste aos desígnios da natureza construindo canais e preparando a terra para o plantio, enquanto vai vivendo com Iori, o “menino da terra” que acabara de perder o pai.`,
    image: 'https://m.media-amazon.com/images/I/91C2KfRtV+L.jpg',
    inStock: 8,
    price: new Prisma.Decimal(29.9),
    rating: 1,
  },
  {
    name: 'One Piece Vol. 100',
    author: 'Eiichiro Oda',
    genreCodes: [0, 1, 7, 3, 8].map((e) => ({ genreId: e })),
    description: `Com todas as estrelas reunidas no topo da fortaleza, Luffy e os Piratas da Nova Geração desafiam Kaido e Big Mom! Será que há alguma chance de vitória contra essa aliança formada entre os dois mais poderosos piratas dos mares?! O que o futuro reserva para essa batalha extrema que está fazendo toda Onigashima tremer?!`,
    image: 'https://m.media-amazon.com/images/I/71xlgzy8YNL.jpg',
    inStock: 32,
    price: new Prisma.Decimal(59.99),
    rating: 1,
  },
  {
    name: 'Slam Dunk Vol. 23',
    author: 'Takehiko Inoue',
    genreCodes: [7, 2, 9].map((e) => ({ genreId: e })),
    description: `Com a entrada de Sakuragi em quadra, a partida começa a melhorar gradualmente para o Shohoku, que ataca ferozmente com as cestas de três pontos do Mitsui. Akagi também se recupera do bloqueio contra Kawata, pois finalmente compreende que derrotá-lo não é essencial para vencer a partida. Por outro lado, qual será a estratégia do Sanno para impedir Sakuragi de pegar todos os rebotes ofensivos?`,
    image: 'https://m.media-amazon.com/images/I/81s-hBdHvcL.jpg',
    inStock: 5,
    price: new Prisma.Decimal(44.9),
    rating: 1,
  },
  {
    name: 'Fullmetal Alchemist Vol. 25',
    author: 'Hiromu Arakawa',
    genreCodes: [0, 1, 7, 2, 3, 8].map((e) => ({ genreId: e })),
    description: `Os humanos escolhidos para serem os “sacrifícios” são levados até o homúnculo original, aquele chamado de “Pai” pelos homúnculos. Seus planos maquiavélicos estão prestes a serem revelados, e faltam apenas algumas peças para o tabuleiro ficar completo. Qual será a próxima jogada?!`,
    image: 'https://m.media-amazon.com/images/I/61QtE9IZvvL.jpg',
    inStock: 12,
    price: new Prisma.Decimal(22.42),
    rating: 1,
  },
  {
    name: 'Naruto Vol. 10',
    author: 'Masashi Kishimoto',
    genreCodes: [0, 1, 11, 8].map((e) => ({ genreId: e })),
    description: `O torneio preliminar da terceira fase está acirrado! Chegou a hora de Lee, que conta apenas com seu taijutsu sobre-humano, enfrentar o misterioso Gaara e seu poder de controlar livremente a areia!!`,
    image: 'https://m.media-amazon.com/images/I/916sfaQ6w4L.jpg',
    inStock: 24,
    price: new Prisma.Decimal(26.69),
    rating: 1,
  },
  {
    name: 'Dragon Ball Vol. 27',
    author: 'Akira Toriyama',
    genreCodes: [0, 1, 7, 12, 8].map((e) => ({ genreId: e })),
    description: `Freeza, tendo se tornado um supermonstro após duas transformações, mata Vegeta! Goku começa sua luta desesperada contra um inimigo de um poder nunca antes visto...!`,
    image: 'https://m.media-amazon.com/images/I/71b4dGvJPyS.jpg',
    inStock: 17,
    price: new Prisma.Decimal(26.29),
    rating: 1,
  },
];

export const genres = [
  'AÇÃO',
  'AVENTURA',
  'DRAMA',
  'FANTASIA',
  'TERROR',
  'PSICOLÓGICO',
  'SEINEN',
  'COMÉDIA',
  'SHONEN',
  'ESPORTE',
  'SLICE OF LIFE',
  'SOBRENATURAL',
  'FICÇÃO CIENTÍFICA',
  'MISTÉRIO',
];
